version: "3.7"

services:
  torch_dev_env:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: torch_dev_env
    env_file:
      - .env
    volumes:
      - ./:/home/working

    # This part is used to enable GPU support
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
