version: "3.7"

services:
  model_name:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: model_name
    ports:
      - "8996:8996"
    env_file:
      - ./.env
    volumes:
      - ./data:/home/working/data:ro

    # This part is used to enable GPU support
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
